theme: jekyll-theme-slate
title: Applied Inversion Methods
description: First course on inversion methods for geoscience undergraduates
name1: Matthew Piggott
address1: Room 4.82, Royal School of Mines
email1: m.d.piggott@imperial.ac.uk
github_username1:  matt-piggott
name2: Rhodri Nelson
address2: Room 4.96, Royal School of Mines
email2: rhodri.nelson@imperial.ac.uk
github_username2:  rhodrin
